INDEX_MESSAGE = "Markdown To Public Link"
INVALID_PASSWORD = "Invalid Password"
BAD_EXTENSION = "Only Markdown Files Can Be Published"
FILE_NOT_FOUND = "File Not Found"
NOT_PUBLISHED = "This File Was Not Published"
UNPUBLISHED_CONFIRMATION = "Unpublished"
LINK_NOT_FOUND = "No Such Link"
